Feature: Funfacts
PartlySaneStudios/partly-sane-cloud pull request #32
Opened 2024-03-05 17:50 UTC by j10a1n15

2024-03-05 19:51 UTC, Su386yt requested changes
Missing documentation

2024-03-05 19:52 UTC, j10a1n15 commented on src/backend/FunFactData.ts
> +const FILE_PATH = "data/constants/fun_facts.json";
https://github.com/PartlySaneStudios/partly-sane-skies-public-data/pull/91

2024-03-05 19:53 UTC, j10a1n15 commented on src/backend/FunFactData.ts
> +const OWNER = "j10a1n15";
i dont think I wanna switch away from pss repo anyway lol

2024-03-06 07:35 UTC, j10a1n15 commented on src/backend/FunFactData.ts
> +    if (funFacts.length == 0 || override) {
Clear the old funfacts of you want to override

2024-03-12 07:05 UTC, merged